### PR TITLE
Batch urls req

### PR DESCRIPTION
**Pull request by rajnmithun**
batch all of the partial hashes together to call api.HashLookup only once.

### CODE REVIEW

**Comment by rajnmithun** [comment]
I signed it!

**Comment by alexwoz** [comment]
LGTM -- thanks for your contribution!

**Comment by rajnmithun** [comment]
thanks for reviewing @alexwoz, can this PR be merged to the master?

**Comment by mafopen** [comment]
@rajnmithun, your changes result in a high number of unnecessary full hash API calls, instead of reducing them.

Only lookups that could not be answered by the database will be added to the batch API request, however, there will always be an API call, even if all the lookups could be answered from the cache or database.

There should be a check for `if len(req.ThreatInfo.ThreatEntries) > 0 {` before sending the API lookup. However, there are also some errors in the accounting/statistics, for example, you are accounting all lookups to `sb.stats.QueriesByAPI`, even if you already counted some before to e.g., `sb.stats.QueriesByCache`.

I'll have a more detailed look later, for now we'll be using a version without this change (c2df0f3).

**Pull request merged**
